<?php


namespace api\controllers;


use common\widgets\HttpSignAuth;
use yii\base\InvalidConfigException;
use yii\base\Model;
use yii\filters\auth\HttpBasicAuth;
use yii\rest\Controller;

class RestController extends Controller
{
    public $modelClass;
    public $updateScenario = Model::SCENARIO_DEFAULT;
    public $createScenario = Model::SCENARIO_DEFAULT;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->modelClass === null) {
            throw new InvalidConfigException('The "ModelClass" property must be set!');
        }
    }

    public function behaviors()
    {
        return [
            'tokenValidate' => [
                'class' => HttpSignAuth::className()
            ],
            'authValidate' => [
                'class' => HttpBasicAuth::className(),
                'optional' => ['register', 'login'],
            ]
        ];
    }

    public function actions()
    {
        return [
            'index' => [
                'class' => 'yii\rest\IndexAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ], 'view' => [
                'class' => 'yii\rest\ViewAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ], 'create' => [
                'class' => 'yii\rest\CreateAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
                'scenario' => $this->createScenario,
            ], 'update' => [
                'class' => 'yii\rest\UpdateAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
                'scenario' => $this->updateScenario,
            ], 'deleta' => [
                'class' => 'yii\rest\DeleteAction',
                'modelClass' => $this->modelClass,
                'checkAccess' => [$this, 'checkAccess'],
            ], 'options' => [
                'class' => 'yii\rest\OptionsAction',
            ],
        ];
    }

    public function verbs()
    {
        return [
            'index' => ['GET', 'HEAD'],
            'view' => ['GET', 'HEAD'],
            'create' => ['POST'],
            'update' => ['PUT', 'PATCH'],
            'delete' => ['DELETE'],
        ];
    }
}
